apiVersion: apps/v1
kind: Deployment 
metadata:
  name: startboot1-deploy
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: startboot1
  replicas: 1 
  template:
    metadata:
      labels:
        app: startboot1
    spec:
      containers:
        - name: startboot1
          image: asif1993/startboot1:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: DB_NAME
              value: mysql
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root           
              
---

apiVersion: v1
kind: Service
metadata:
  name: startboot1-svc
  namespace: webapps
spec:
  selector:
    app: startboot1
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: LoadBalancer                                     